version: '3.8'
services:
  db:
    image: mysql:latest
    container_name: mysql-test-db
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=Employees
      - MYSQL_ROOT_PASSWORD=root12345
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=12345
    ports:
      - '3306:3306'
    volumes:
      - db:/Users/rahulupadhyay/Documents/code/mysql/data
volumes:
  db:
    driver: local